### ISSUE TITLE
Broken version list

### ISSUE THREAD

**Issue by maxsupermanhd** [daydev/FactorioWireShortcuts#5]
Why you have release with lesser version on top?
![image](https://user-images.githubusercontent.com/20772987/80870599-2ddfdd00-8cb0-11ea-82f0-ae34b78a8831.png)

**Comment by daydev** [comment]
It's to backport the latest updates to 0.17. 0.3.175 is exactly the same as 0.4.3, but marked for Factorio 0.17, the latest stable.
